# /anaconda/envs/py38_default/bin/python3

# Import required packages
import sys

dict = {}  # Initialize dictionary to store data stats for each column

for line in sys.stdin:  # for each line in ouput generated by mapper
    line = line.strip()  # Strip the line to remove white dpaces
    col_name, null_c, min, max, sum, count = line.split(
        "\t"
    )  # sperate values by \t delimeter
    null, n_count = null_c.split(":")  # Get null counts
    min, min_val = min.split(":")  # Get min value
    max, max_val = max.split(":")  # Get max value
    sum, sum_val = sum.split(":")  # Get total sum of values
    t_count, count_val = count.split(":")  # Get non-null count

    # Change to numeric datatypes
    n_count = int(n_count)
    min_val = float(min_val)
    max_val = float(max_val)
    sum_val = float(sum_val)
    count_val = int(count_val)

    if col_name in dict:  # If column has already entry in dictionary
        if col_name in ["iso_code", "country"]:
            # For non-numeric column, add null count
            dict[col_name][null] += n_count
        else:
            # For numeric columns,
            dict[col_name][null] += n_count  # Add null count

            # If current minimum is less then, present - replace min val
            dict[col_name][min] = (
                min_val if min_val < dict[col_name][min] else dict[col_name][min]
            )
            # If current maximum is more then, present - replace max val
            dict[col_name][max] = (
                max_val if max_val > dict[col_name][max] else dict[col_name][max]
            )
            dict[col_name][sum] += sum_val  # add total sum
            dict[col_name][t_count] += count_val  # add count

    else:
        # If column doesn't exist, add to dictioanry
        dict[col_name] = {
            null: n_count,
            min: min_val,
            max: max_val,
            sum: sum_val,
            t_count: count_val,
        }

for column, val in dict.items():
    # Calculate the mean for non numeric columns
    if col_name in ["iso_code", "country"]:
        print(f"{column}\tNull_Count:{val['null_count']}\tMin:NA\tMax:NA\tMean:NA")
    else:
        mean_val = round(val["sum"] / int(val["count"]), 3)
        print(
            f"{column}\tNull_Count:{val['null_count']}\tMin:{val['min']}\tMax:{val['max']}\tMean:{mean_val}"
        )
