#!/usr/bin/python3

import sys

dict = {}  # Initialize dictionary to store data stats for each column

for line in sys.stdin:  # for each line in output generated by mapper
    line = line.strip()  # Strip the line to remove white spaces
    col_name, null_c, min, max, sum, count = line.split(
        "\t"
    )  # separate values by \t delimiter
    null, n_count = null_c.split(":")  # Get null counts
    min_label, min_val = min.split(":")  # Get min value
    max_label, max_val = max.split(":")  # Get max value
    sum_label, sum_val = sum.split(":")  # Get total sum of values
    t_count_label, count_val = count.split(":")  # Get non-null count

    # Change to numeric datatypes
    n_count = int(n_count)
    min_val = float(min_val) if min_val != "NA" else None
    max_val = float(max_val) if max_val != "NA" else None
    sum_val = float(sum_val) if sum_val != "NA" else None
    count_val = int(count_val) if count_val != "NA" else None

    if col_name in dict:  # If column has already entry in dictionary
        dict[col_name][null] += n_count
        dict[col_name][min_label] = (
            min(min_val, dict[col_name][min_label])
            if min_val is not None
            else dict[col_name][min_label]
        )
        dict[col_name][max_label] = (
            max(max_val, dict[col_name][max_label])
            if max_val is not None
            else dict[col_name][max_label]
        )
        dict[col_name][sum_label] += sum_val if sum_val is not None else 0
        dict[col_name][t_count_label] += count_val if count_val is not None else 0
    else:
        dict[col_name] = {
            null: n_count,
            min_label: min_val,
            max_label: max_val,
            sum_label: sum_val,
            t_count_label: count_val,
        }

for column, val in dict.items():
    mean_val = (
        round(val[sum_label] / val[t_count_label], 3)
        if val[t_count_label] > 0
        else "NA"
    )
    min_val = val[min_label] if val[min_label] is not None else "NA"
    max_val = val[max_label] if val[max_label] is not None else "NA"
    print(
        "{}\t\t\tNull_Count:{}\t\tMin:{}\t\tMax:{}\t\tMean:{}".format(
            column, val[null], min_val, max_val, mean_val
        )
    )
