#!/anaconda/envs/py38_default/bin/python3

# Import required packages
import sys

dict = {}  # Initialize dictionary to store null_percentage

for line in sys.stdin:  # for each line in ouput generated by mapper
    line = line.strip()  # Strip the line to remove white dpaces
    year, null_c, count = line.split("\t")  # sperate values by \t delimeter
    null, n_count = null_c.split(":")  # Get null counts
    t_count, count_val = count.split(":")  # Get total count

    # Change to numeric datatypes
    n_count = int(n_count)
    count_val = int(count_val)

    if year in dict:
        dict[year][null] += n_count
        dict[year][t_count] += count_val

    else:
        dict[year] = {null: n_count, t_count: count_val}

for year, val in dict.items():
    null_percent = round((val[null] / val[t_count]) * 100, 2)
    print(f"Data starting - {year}\tNull percentage: {null_percent}")
